### ISSUE TITLE
Custom Namespaces

### ISSUE THREAD

**Issue by ckorhonen** [sj26/sidekiq-cloudwatchmetrics#7]
Love the gem, we are using it for autoscaling worker instances based on queue depth.

One challenge that we have encountered is this doesn't really play well with multiple environments, or multiple different types of worker instance since metrics are published to the same namespace.

I'd love a way to customize this on initialization, so for example:

```ruby
Sidekiq::CloudWatchMetrics.enable!(client: ..., namespace: "Sidekiq-Staging")
```

**Comment by sj26** [comment]
Sounds like a nice idea!

**Comment by ckornacker** [comment]
We're using it for the exact same reason and utilize `additional_dimensions` to set the environment/cluster/worker... i.e.:
```ruby
Sidekiq::CloudWatchMetrics.enable!(additional_dimensions: { 'ClusterName' => 'Sidekiq-Staging' })
```

By the way, there seems to be a mixup with the [gem versions](https://rubygems.org/gems/sidekiq-cloudwatchmetrics/versions/). The highest version (2.0.0) is outdated, the latest code is 1.2.0.

**Comment by ndbroadbent** [comment]
I also needed this for multiple environments in the same AWS account, so I've opened a PR: #13

Thanks for the tip about ClusterName, @ckorhonen. I'm just not too sure how to use this additional dimension for my [Convox autoscaling config](http://sourcebottle.net/autoscaling-sidekiq-workers-on-convox)

**Comment by ckorhonen** [comment]
@ndbroadbent I think you would use it like this in your `convox.yml`:

```
    scale:
      count: 1-10
      targets:
        custom:
          Sidekiq-Staging/EnqueuedJobs:
            aggregate: max
            value: 1000
```

**Comment by ckornacker** [comment]
I haven't used convox before, but according to the docs using dimensions would look something like this:
```
    scale:
      count: 1-10
      targets:
        custom:
          Sidekiq/EnqueuedJobs:
            aggregate: max
            value: 1000
            dimensions:
              ClusterName: Sidekiq-Staging
```
